const blacklistAll = [
  "singleplayer", "Singleplayer",
  "multiplayer", "Multiplayer",
  "co-op", "Co-op",
  "local-co-op", "Local Co-Op",
  "online-co-op", "Online Co-Op",
  "shared-split-screen", "Shared/Split Screen",
  "cross-platform-multiplayer", "Cross-Platform Multiplayer",
  "steam-achievements", "Steam Achievements",
  "steam-cloud", "Steam Cloud",
  "steam-trading-cards", "Steam Trading Cards",
  "steam-workshop", "Steam Workshop",
  "in-app-purchases", "In-App Purchases",
  "valve-anti-cheat", "Valve Anti-Cheat",
  "partial-controller-support", "Partial Controller Support",
  "full-controller-support", "Full Controller Support",
  "remote-play-on-phone", "Remote Play on Phone",
  "remote-play-on-tablet", "Remote Play on Tablet",
  "remote-play-on-tv", "Remote Play on TV",
  "remote-play-together", "Remote Play Together",
  "captions-available", "Captions available",
  "commentary-available", "Commentary available",
  "includes-level-editor", "Includes level editor",
  "exclusive", "Exclusive",
  "atmospheric", "Atmospheric",
  "great-soundtrack", "Great Soundtrack",
  "story-rich", "Story Rich",
  "funny", "Funny",
  "classic", "Classic",
  "beautiful", "Beautiful",
  "masterpiece", "Masterpiece",
  "cult-classic", "Cult Classic",
  "difficult", "Difficult",
  "casual", "Casual",
  "relaxing", "Relaxing",
  "family-friendly", "Family Friendly",
  "short", "Short",
  "indie", "Indie",
  "action", "Action",
  "adventure", "Adventure",
  "rpg", "RPG",
  "strategy", "Strategy",
  "simulation", "Simulation",
  "shooter", "Shooter",
  "arcade", "Arcade"
]

export const blacklist = blacklistAll.map(item => item.toLowerCase())